- administrator/language/de-DE/de-DE.lib_joomla.ini
- language/de-DE/de-DE.lib_joomla.ini
siehe: https://github.com/joomla/joomla-cms/commit/25cc353df60734e435864a288dfbf0eaf5fc9826
> Standardizing the install paths for discover_install 

- language/de-DE/de-DE.tpl_protostar.ini
siehe: https://github.com/joomla/joomla-cms/commit/e06af894a02c1d7737c6587fdbec4dcc167ee34b
> Hex colors protostar

- administrator/language/de-DE/de-DE.com_cpanel.ini
siehe: https://github.com/joomla/joomla-cms/commit/50842e938c572b141bc6db1ca415af6883569623
> Removing one superfluous language string

- administrator/language/de-DE/de-DE.localise.php
- language/de-DE/de-DE.localise.php
@sisko1990 hier eine Datei die noch auf 2013 steht :smile:
> Copyright für die de-DE.localise.php

- administrator/language/de-DE/de-DE.lib_joomla.ini
- language/de-DE/de-DE.lib_joomla.ini
siehe: https://github.com/joomla/joomla-cms/commit/544269672cb826a4d6d1d44a22760bac35f75d15
> Fehlende Sprachstrings für 3.4

- administrator/language/de-DE/de-DE.com_installer.ini
siehe: https://github.com/joomla/joomla-cms/commit/e1bd37f0b6242670fe6b1ad7741729db75cff000
> [3.4.1] Target blank on external link

- administrator/language/de-DE/de-DE.com_installer.ini
Einfacher Syntax Fehler in der Datei: de-DE.com_installer.ini
> Einfacher Syntax Fehler in der Datei: de-DE.com_installer.ini

- administrator/language/de-DE/de-DE.com_postinstall.ini
siehe: https://github.com/joomla/joomla-cms/commit/e5dfc6ed5acf3f9e5dad57228246296a3869a094
> Update de-DE.com_postinstall.ini (cosmetic)

- administrator/language/de-DE/de-DE.com_modules.sys.ini
siehe: https://github.com/joomla/joomla-cms/commit/5015f2b2c873a3f2b0b77e38a60c82b2eed16985
> Make module redirect configurable

- language/de-DE/de-DE.lib_fof..ini
- language/de-DE/install.xml
siehe: https://github.com/joomla/joomla-cms/commit/a1d106a6d8fdb7522c493e1a6d27f7c64f4c8b78 und: https://github.com/joomla/joomla-cms/commit/777030755e401cf512d76441263abc5e21827fb4
Außerdem wird in der install.xml alle leerzeichen durch tabs ersetzt :smile:
> [3.4.2] Final Update to FOF2.x

- language/de-DE/de-DE.localise.php
siehe: http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.pkg.html
> Ein paar Leerzeichen und der @link tag ;) Es gibt keine @source tag :)

- administrator/language/de-DE/de-DE.localise.php
- language/de-DE/de-DE.localise.php
ich wusste garnicht das es zwei unterschiedliche Dateien gibt ;)
Hier ein sync der frontend und backend Datei. Danke @bakual ;)
> Sync de-DE.localise.php

- administrator/language/de-DE/de-DE.com_installer.ini
Hi,
durch diesen Fehler wird der URL nicht richtig aufgebaut und man bekommt einen Fehler beim Download ;)
> Fehler in COM_INSTALLER_PACKAGE_DOWNLOAD_FAILED

- installation/language/de-DE/de-DE.ini
Fehler in der Rechtschreibung behoben "zusätztlich" in "zusätzlich" geändert.
> Rechtschreibefehler behoben

- installation/language/de-DE/de-DE.ini
Hinzufügen von (DE-CH-AT) zum Nativenamen
> Hinzufügen von (Deutschland) zum Nativenamen

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Templates für Issues und PR's die Dateien sollten natürlich aus der finalen build entfernt werden ;)
Github Doku: https://github.com/blog/2111-issue-and-pull-request-templates
> GitHub issue und pr templates

- administrator/language/de-DE/de-DE.com_associations.ini
- administrator/language/de-DE/de-DE.com_associations.sys.ini
Hier kommen zwei neue Dateien für 3.7:
> de-DE.com_associations.ini + de-DE.com_associations.sys.ini

- administrator/language/de-DE/de-DE.plg_fields_calendar.sys.ini
Neue Datei angelegt und Übersetzung 
- de-DE.plg_fields_calendar.sys.ini
> Übersetzung (fields) de-DE.plg_fields_calendar.sys.ini

- administrator/language/de-DE/de-DE.plg_fields_checkboxes.ini
- administrator/language/de-DE/de-DE.plg_fields_checkboxes.sys.ini
Übersetzung und Anlegen fehlender Sprachparameter für 
de-DE.plg_fields_checkboxes.ini
de-DE.plg_fields_checkboxes.sys.ini
> Übersetzung (fields) de-DE.plg_fields_checkboxes.ini + sys.ini

- administrator/language/de-DE/de-DE.plg_editors-xtd_fields.ini
- administrator/language/de-DE/de-DE.plg_editors-xtd_fields.sys.ini
- administrator/language/de-DE/de-DE.plg_editors-xtd_menu.ini
- administrator/language/de-DE/de-DE.plg_editors-xtd_menu.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_sql.ini
- administrator/language/de-DE/de-DE.plg_fields_sql.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_text.ini
- administrator/language/de-DE/de-DE.plg_fields_text.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_textarea.ini
- administrator/language/de-DE/de-DE.plg_fields_textarea.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_url.ini
- administrator/language/de-DE/de-DE.plg_fields_url.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_user.ini
- administrator/language/de-DE/de-DE.plg_fields_user.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_usergrouplist.ini
- administrator/language/de-DE/de-DE.plg_fields_usergrouplist.sys.ini
- administrator/language/de-DE/de-DE.plg_quickicon_phpversioncheck.ini
- administrator/language/de-DE/de-DE.plg_quickicon_phpversioncheck.sys.ini
- administrator/language/de-DE/de-DE.plg_system_fields.ini
- administrator/language/de-DE/de-DE.plg_system_fields.sys.ini
- administrator/language/de-DE/install.xml
Fehlende Dateien welche noch übersetzt werden müssen
Sowie Anpassungen an der install.xml
> Fehlende Dateien welche noch übersetzt werden müssen

- administrator/language/de-DE/de-DE.plg_content_fields.ini
> 2 Strings hinzugefügt

- administrator/language/de-DE/de-DE.plg_fields_editor.ini
> Neue Zeilen hinzugefügt für J! 3.7

- administrator/language/de-DE/de-DE.plg_fields_integer.sys.ini
> 2 neue Zeilen hinzugefügt für J! 3.7

- administrator/language/de-DE/de-DE.plg_fields_media.ini
- administrator/language/de-DE/de-DE.plg_fields_media.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_radio.ini
- administrator/language/de-DE/de-DE.plg_fields_radio.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_sql.ini
- administrator/language/de-DE/de-DE.plg_fields_sql.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_text.ini
- administrator/language/de-DE/de-DE.plg_fields_textarea.ini
- administrator/language/de-DE/de-DE.plg_fields_textarea.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_media.ini
- administrator/language/de-DE/de-DE.plg_fields_media.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_radio.ini
- administrator/language/de-DE/de-DE.plg_fields_radio.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_sql.ini
- administrator/language/de-DE/de-DE.plg_fields_sql.sys.ini
- administrator/language/de-DE/de-DE.plg_fields_text.ini
- administrator/language/de-DE/de-DE.plg_fields_textarea.ini
- administrator/language/de-DE/de-DE.plg_fields_textarea.sys.ini
Übersetzung by @chmst
> Fields Plugin Übersetzungen

- installation/language/de-DE/de-DE.xml
leerzeichen zu tabs in der installer datei
> spaces to tabs

- administrator/language/de-DE/de-DE.mod_sampledata.ini
> New file for J! 3.8.0

- administrator/language/de-DE/de-DE.mod_menu.ini
##Added lines:
[47] MOD_MENU_FIELD_PRESET_LABEL="Voreinstellung wählen"
[48] MOD_MENU_FIELD_PRESET_DESC
[73] ; comments
[74] ; comments
##Changed lines:
[46] MOD_MENU_FIELD_MENUTYPE_OPTION_PREDEFINED
> Update for Joomla! 3.8

- administrator/language/de-DE/de-DE.plg_sampledata_blog.sys.ini
> New file for Joomla! 3.8

- administrator/language/de-DE/de-DE.ini
> Show the root user configuration to any superadmin when enabeld

- administrator/language/de-DE/de-DE.xml
- administrator/language/de-DE/install.xml
- installation/language/de-DE/de-DE.xml
- installation/localise.xml
- language/de-DE/de-DE.xml
- language/de-DE/install.xml
- pkg_de-DE.xml
Move cosmetic version tag to the correct version
> Move cosmetic version tag to the correct version

- administrator/language/de-DE/de-DE.plg_editors_tinymce.ini
See change: "verlohren" -> "verloren"
> Little typo in PLG_TINY_LEGACY_WARNING

- administrator/language/de-DE/de-DE.com_redirect.ini
Pull Request für Issue #311 .
Setzt "Plugin" vor den String.
Und vereinheitlicht die Strings in https://github.com/joomlagerman/joomla/blob/49ed07ecc6f6bc4fa3af10cb3dfffb189aba59a0/administrator/language/de-DE/de-DE.com_redirect.ini#L89 und https://github.com/joomlagerman/joomla/blob/49ed07ecc6f6bc4fa3af10cb3dfffb189aba59a0/administrator/language/de-DE/de-DE.com_redirect.ini#L91
> fix #311 and unifies the speech strings 89 and 91

- administrator/language/de-DE/de-DE.plg_system_sessiongc.ini
- administrator/language/de-DE/de-DE.plg_system_sessiongc.sys.ini
Pull Request für Issue #322 
https://github.com/joomla/joomla-cms/pull/19687/files
> [3.8.6] The One Right Session Management Configuration For Joomla! 3 Plugin

- administrator/language/de-DE/de-DE.plg_captcha_recaptcha.ini
Pull Request für Issue #324
https://github.com/joomla/joomla-cms/pull/19648/files
> reCAPTCHA V1

- administrator/language/de-DE/de-DE.com_joomlaupdate.ini
Pull Request für Issue https://github.com/joomlagerman/joomla/issues/433
> [3.9] light checksum for joomlaupdate & Make sure the update hash checker produces the correct result

- language/de-DE/de-DE.mod_articles_latest.ini
https://github.com/joomlagerman/joomla/issues/456
> [3.9] [mod_articles_latest] Option for choose an specific author(s)

- administrator/language/de-DE/de-DE.plg_user_contactcreator.ini
3 missung punctuation marks
3.9-dev
> Punctuation mark plg_user_contactcreator

- administrator/language/de-DE/de-DE.plg_privacy_user.ini
- administrator/language/de-DE/de-DE.plg_privacy_user.sys.ini
Pull Request für Issue #499 .
translation
3.9-dev
> [3.9] plg_privacy_user.ini & plg_privacy_user.sys.ini #499

- administrator/language/de-DE/de-DE.plg_installer_webinstaller.ini
https://github.com/joomla/joomla-cms/pull/21950
PS: Wir sollten abwarten bis die CMS PR gemerged wurde da es ja dort ggf. noch Änderungen gibt
> [3.9] Adjustments for upcoming Install from Web plugin update

- language/de-DE/de-DE.mod_stats.ini
Pull Request für Issue https://github.com/joomlagerman/joomla/issues/367#issuecomment-417937627
Die Übersetzung zwischen Backend und Frontend synchronisieren
@n-at-work https://github.com/joomlagerman/joomla/issues/367#issuecomment-417937627
> [3.9] Sync the translation for the view hits translation

- administrator/language/de-DE/de-DE.ini
https://github.com/joomla/joomla-cms/pull/21954
> [3.9] Unused string. Code was modified to use a JGLOBAL one 

- administrator/language/de-DE/de-DE.plg_system_logrotation.ini
- administrator/language/de-DE/de-DE.plg_system_logrotation.sys.ini
Pull Request für Issue #502 .
translation
3.9-dev
> [3.9]plg_system_logrotation.ini & plg_system_logrotation.sys.ini #502

- administrator/language/de-DE/de-DE.plg_quickicon_privacycheck.ini
- administrator/language/de-DE/de-DE.plg_quickicon_privacycheck.sys.ini
Pull Request für Issue #500  .
translation
3.9-dev
> [3.9] plg_quickicon_privacycheck.ini & plg_quickicon_privacycheck.sys.ini

- administrator/language/de-DE/de-DE.plg_privacy_contact.ini
- administrator/language/de-DE/de-DE.plg_privacy_contact.sys.ini
Pull Request für Issue #496 .
translation
3.9-dev
> [3.9] plg_privacy_contact.sys.ini & plg_privacy_contact.ini

- administrator/language/de-DE/de-DE.mod_privacy_dashboard.ini
- administrator/language/de-DE/de-DE.mod_privacy_dashboard.sys.ini
Pull Request für Issue #492 .
translation
3.9-dev
> [3.9] mod_privacy_dashboard.ini & mod_privacy_dashboard.sys.ini

- administrator/language/de-DE/de-DE.plg_content_confirmconsent.ini
- administrator/language/de-DE/de-DE.plg_content_confirmconsent.sys.ini
Pull Request für Issue #494  .
translation
3.9-dev
Unfortunately, this is a bit more complex in German. I have created a mix of privacy policy and privacy notice.
For the German consumer, the plugin but rather be searched under Privacy Policy and not Privacy Note.
> [3.9] plg_content_confirmconsent.ini & plg_content_confirmconsent.sys.ini

- administrator/language/de-DE/de-DE.mod_latestactions.ini
- administrator/language/de-DE/de-DE.mod_latestactions.sys.ini
Pull Request für Issue #491 .
translation
3.9-dev
> [3.9] mod_latestactions.ini & mod_latestactions.sys.ini

- administrator/language/de-DE/de-DE.plg_content_confirmconsent.ini
- administrator/language/de-DE/de-DE.plg_user_terms.ini
Artikel -> Beitrag
Beitrag
Artikel
3.9-dev
> [3.9] Update de-DE.plg_user_terms.ini

- administrator/language/de-DE/de-DE.plg_content_confirmconsent.ini
- administrator/language/de-DE/de-DE.plg_content_confirmconsent.sys.ini
> [3.9] Update de-DE.plg_content_confirmconsent.ini

- administrator/language/de-DE/de-DE.plg_privacy_actionlogs.ini
- administrator/language/de-DE/de-DE.plg_privacy_actionlogs.sys.ini
Pull Request für Issue #495 .
translation
3.9-dev
> [3.9] plg_privacy_actionlogs.ini & plg_privacy_actionlogs.sys.ini

- media/system/js/fields/calendar-locales/de.js
https://github.com/joomla/joomla-cms/pull/22026/files
> [FIX] Calendar wrong locale variable

- administrator/language/de-DE/de-DE.com_privacy.ini
Changed string COM_PRIVACY_EXTENSION_CAPABILITY_PERSONAL_INFO
> Grammar error

- language/de-DE/de-DE.mod_feed.ini
sorting and double string usage
3.9-dev
> sorting and double string usage

- administrator/language/de-DE/de-DE.plg_system_privacyconsent.ini
Pull Request für Issue #556 .
wording
3.9-dev
> [3.9] Übersetzung von "Expiration" zu Ablauf

- language/de-DE/de-DE.com_privacy.ini
und Token ist Maskulinum: https://www.korrekturen.de/genus/der-oder-das-token.shtml
> Persönliche Anrede in allgemeine Formulierung umgewandelt

- administrator/language/de-DE/de-DE.plg_content_confirmconsent.ini
https://github.com/joomla/joomla-cms/pull/22222
> [3.9] Missing strings in plugin_confirmconsent

- administrator/language/de-DE/de-DE.plg_system_privacyconsent.ini
https://github.com/joomla/joomla-cms/pull/22192
> [plg_system_privacyconsent] - log privacy consent

- administrator/language/de-DE/de-DE.plg_actionlog_joomla.ini
Pull Request für Issue #592 .
add missing strings and translation
3.9-beta
> Correcting plg_actionlog_joomla language strings #22342

- administrator/language/de-DE/de-DE.com_users.ini
Pull Request für Issue #599  .
add new string
3.8.12
wait for merge: https://github.com/joomla/joomla-cms/pull/22434
> [3.8.12] "Abmeldeweiterleitungstyp": Falsche Information im Tooltip

- administrator/language/de-DE/de-DE.plg_system_actionlogs.ini
von ä nach a
danke @dynamicflight und @JUG-Nuremberg
Benutzeraktivitäten
Benutzeräktivitäten
3.9-beta
> typo in de-DE.plg_system_actionlogs.ini

- administrator/language/de-DE/de-DE.plg_system_highlight.ini
- administrator/language/de-DE/de-DE.plg_system_highlight.sys.ini
Pull Request für Issue #630 .
3.9-beta
thanks @franz-wohlkoenig
> [3.8.13] Plugin "System - Highlight": Textkorrektur

- administrator/language/de-DE/de-DE.plg_content_fields.ini
Pull Request für Issue #623 .
3.9-beta
thanks @franz-wohlkoenig
> [3.8.13] Plugin "Inhalt - Felder": Textkorrektur

- administrator/language/de-DE/de-DE.plg_system_updatenotification.ini
Textkorrektur "Kommata" statt "Kommas".
> de-DE.plg_system_updatenotification.ini

- administrator/language/de-DE/de-DE.plg_privacy_consents.ini
- administrator/language/de-DE/de-DE.plg_privacy_consents.sys.ini
Pull Request für Issue #642 .
add two new files and translation
3.9-RC2
> [3.9] Add privacy plugin for exporting consent data, enable actionlogs privacy plugin by default

- administrator/language/de-DE/de-DE.com_actionlogs.sys.ini
Pull Request für Issue #646 .
add two new strings
translation
3.9.0
> [3.9.1] Add the default.xml file to useractions default view

- administrator/language/de-DE/de-DE.plg_privacy_actionlogs.ini
- administrator/language/de-DE/de-DE.plg_privacy_actionlogs.sys.ini
Pull Request für Issue #651 .
fix
3.9.0
> [3.9] Remove factually incorrect sentence

- administrator/language/de-DE/de-DE.xml
- administrator/language/de-DE/install.xml
- installation/language/de-DE/de-DE.xml
- language/de-DE/de-DE.xml
- language/de-DE/install.xml
- pkg_de-DE.xml
String that identifies the version of Joomla for which this extension is developed.
Change from version="3.8" to version="3.9"
3.9.1
> Change version no to 3.9

- administrator/language/de-DE/de-DE.com_privacy.ini
https://github.com/joomla/joomla-cms/pull/22888/files
> Privacy dashboard: direct access to the privacy consent plugin

- administrator/language/de-DE/de-DE.plg_editors_none.ini
- administrator/language/de-DE/de-DE.plg_editors_none.sys.ini
Fixed PR #674 and #673
Thank you very much @JKusber for the hint.
This PR contains only the necessary file changes.
in der Konfiguration bzw. beim Benutzer als Editor: Editor - Keine wählen.
Editor - Keine**r**
Editor - Keine
3.9.2
Fixed also the plugin description. Better understanding of what the plugin does.
> None editor wording

- administrator/language/de-DE/de-DE.com_contact.ini
- language/de-DE/de-DE.com_contact.ini
Pull Request für Issue #680 .
Add two comments in com-contact ini files.
Some strings are deprecated and will be removed in 4.0
3.9.2
> [staging] Deleting unused Contacts "banned" fields

- administrator/language/de-DE/de-DE.plg_system_debug.ini
Call Stack ist ein fester Begriff cc @snipersister
> Aufrufstapel vs. Call Stack

- administrator/language/de-DE/de-DE.com_media.ini
https://github.com/joomla/joomla-cms/commit/1547f8e76000a22d9befc2551ca9929f5d2d0c56
> COM_MEDIA_ERROR_WARNINVALID_FOLDER

- language/de-DE/de-DE.tpl_cassiopeia.ini
- language/de-DE/de-DE.tpl_cassiopeia.sys.ini
> [4.0] Add tpl cassiopeia

- administrator/language/de-DE/de-DE.com_modules.ini
https://github.com/joomla/joomla-cms/pull/24635/files
> Prevent to save too large module content > 65535

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Pull Request für Issue https://github.com/joomlagerman/joomla/issues/727
Neue Issue und PR Templates
> [META] Neue Issue und PR Templates

- administrator/language/de-DE/de-DE.lib_joomla.ini
- language/de-DE/de-DE.lib_joomla.ini
Pull Request für Issue #749 .
add 6 new strings in 2 files.
translation
See https://github.com/joomla/joomla-cms/pull/25954
> Missing Strings #25954

- administrator/language/de-DE/joomla.ini
- language/de-DE/joomla.ini
Pull Request für Issue #888 .
add new strings and translation
both
> [4.0] Meta Description character count

- administrator/language/de-DE/joomla.ini
- language/de-DE/joomla.ini
Pull Request für Issue #908 .
add one new string and translation
both
> [4.0] Open in new window

- installation/language/de-DE/joomla.ini
Pull Request für Issue #903 .
add new string and translation
during installation
> [4.0] Missing J installation error language string

- administrator/language/de-DE/joomla.ini
Pull Request für Issue #901 .
add warning string
backend
> [4.0] Internet Explorer message

- administrator/language/de-DE/install.xml
- administrator/language/de-DE/langmetadata.xml
- installation/language/de-DE/langmetadata.xml
- installation/localise.xml
- language/de-DE/install.xml
- language/de-DE/langmetadata.xml
Pull Request für Issue #930 .
delete version number in 6 xml files
> [4.0] Delete version number in manifest

- administrator/language/de-DE/joomla.ini
- language/de-DE/joomla.ini
Pull Request für Issue #933 .
Fixes #933 
api/language/en-GB/joomla.ini will be fixed with PR #891 
both
> [4.0] helpsite removal

- .github/auto_assign.yml
- .github/workflows/auto-assign.yml
- .github/workflows/greetings.yml
This PR adds workflows and actions.
The following is added.
Greetings: Everyone who adds an issue or PR for the first time will get a thank you.
Furthermore the group joomlagerman/reviewer is added automatically as reviewers :)
> GitHub workflows

- .github/auto_assign.yml
- .github/workflows/auto_assign_action.yml
@zero-24 please check.
Something was wrong before and no reviewers and assignees were added. Now it should fit.
> Workflow fix 1

- README.md
> [4.0] Update README.md

- README.md
> [3.10] Update README.md

- installation/language/de-DE/de-DE.xml
- installation/sql/mysql/localise.sql
Pull Request für Issue #976 .
2019 -> 2020
> Correction of obsolete annual figures

- administrator/language/de-DE/de-DE.ini
- language/de-DE/de-DE.ini
Pull Request für Issue #980 .
add two new strings
translation
both
> Added language constant INFO

- administrator/language/de-DE/plg_extension_namespacemap.ini
- administrator/language/de-DE/plg_extension_namespacemap.sys.ini
Pull Request für Issue #978 .
change /
backend
> [4.0] namespacemap plugin

- administrator/language/de-DE/de-DE.lib_joomla.ini
- language/de-DE/de-DE.lib_joomla.ini
Pull Request für Issue #985 .
add two new strings
@zero-24 : the translation is covered in Issue #808 and PR #795
both
> [4.0] Missing language strings

- administrator/language/de-DE/plg_user_token.ini
- administrator/language/de-DE/plg_user_token.sys.ini
Pull Request für Issue #1005 .
add API
backend
> [4.0] API Token

- administrator/language/de-DE/plg_user_token.ini
- administrator/language/de-DE/plg_user_token.sys.ini
Pull Request für Issue #1006 .
mostly reorder
backend
> [4.0] Token plugins

- administrator/language/de-DE/de-DE.localise.php
- language/de-DE/de-DE.localise.php
Pull Request für Issue #1039 .
both
> Adjust en-GB.localise.php with string based suffixes

- administrator/language/de-DE/de-DE.com_joomlaupdate.ini
Pull Request für Issue #1032 .
fix string
backend
> [3.10] Add the explanation about the compatibility tag to the pre update checker

- administrator/language/de-DE/plg_fields_sql.ini
Pull Request für Issue #1025 .
delete one line
backend
> [4.0] Remove unused PLG_FIELDS_SQL_RULES_ADAPTED

- installation/language/de-DE/joomla.ini
Pull Request für Issue #1020 .
replace "installation" with string variable
backend
> [4.0] Installation: preventing translation of the "installation" folder

- administrator/language/de-DE/plg_system_webauthn.ini
Pull Request für Issue #1004 .
new wording
backend
> [4.0] webauthn username notice

- administrator/language/de-DE/mod_messages.ini
Pull Request für Issue #1119 .
fix tow typos
backend
> [4.0] Typo Privte

- pkg_de-DE.xml
Pull Request für Issue #1161 .
Delete "Full" from pkg_de-DE.xml
Backend
> [3.x] delete word "Full" from pkg_de-DE.xml

- administrator/language/de-DE/de-DE.plg_actionlog_joomla.ini
Pull Request für Issue #1182 .
add new string
translation
backend
> [3.9] Log the event on actionlogs when Joomla update

- administrator/language/de-DE/de-DE.ini
Pull Request für Issue #1183 .
add Deprecated hint
backend
> [3.9] Remove unneeded strings from robots parameter

- administrator/language/de-DE/de-DE.com_joomlaupdate.ini
Pull Request für Issue #1219 .
fix typo
> [staging] typo "EinE Aktualisierung..."

- administrator/language/de-DE/de-DE.plg_actionlog_joomla.ini
Pull Request für Issue #1232  .
add new string
translation
backend
> [3.9][plg_actionlogs] self activate account

- administrator/language/de-DE/de-DE.plg_actionlog_joomla.ini
Pull Request für Issue #1238 .
add new string
translation
backend
> [3.9] Log the from version on actionlogs when Joomla update

- language/de-DE/com_users.ini
Pull Request für Issue #1110 .
delete one string
frontend
> [4.0] com_users front end forms

- language/de-DE/com_tags.ini
Pull Request für Issue #1291 .
fixes
frontend
> [4.0] Frontend: correcting Tags layouts

- administrator/language/de-DE/plg_installer_override.ini
Pull Request für Issue #1138 .
rename strings
backend
> [4.0] installer override plugin: Fix wrong plural string format

- installation/language/de-DE/joomla.ini
Pull Request für Issue #1304 .
add new string
translation
installation
> [4.0] [a11y] add sr-only text to first column of table head

- api/language/de-DE/joomla.ini
Pull Request für Issue #1114 .
just api was not updated
api
> [4.0] Remove string that was only used in the GMail plugin

- administrator/language/de-DE/plg_extension_namespacemap.ini
- administrator/language/de-DE/plg_extension_namespacemap.sys.ini
Pull Request für Issue #1139 .
just namespace path
backend
> [4.0] namespace path

- administrator/language/de-DE/plg_workflow_featuring.ini
- administrator/language/de-DE/plg_workflow_featuring.sys.ini
- administrator/language/de-DE/plg_workflow_notification.ini
- administrator/language/de-DE/plg_workflow_notification.sys.ini
- administrator/language/de-DE/plg_workflow_publishing.ini
- administrator/language/de-DE/plg_workflow_publishing.sys.ini
Pull Request für Issue #1338  .
add 6 new files
translation is missing!
> [4.0] missing plg_workflow*.ini files

- administrator/language/de-DE/plg_authentication_cookie.ini
- administrator/language/de-DE/plg_authentication_cookie.sys.ini
Pull Request für Issue #1137 .
rename strings
backend
> [4.0] Normalizing authentication cookie plugin lang strings

- administrator/language/de-DE/plg_authentication_joomla.ini
- administrator/language/de-DE/plg_authentication_joomla.sys.ini
Pull Request für Issue #1136 .
rename strings
backend
> [4.0] Normalizing authentication joomla plugin strings

- administrator/language/de-DE/plg_content_imagelazyload.sys.ini
Pull Request für Issue #1239
Drop plg_content_imagelazyload.sys.ini 
none
> [4.0] Pluginless lazyloading for the core

- administrator/language/de-DE/plg_editors_tinymce.ini
Pull Request für Issue #1154 
add missing string
backend
> [4.0] tinymce plugin missing string [a11y] 

- language/de-DE/joomla.ini
Pull Request für Issue #1332 .
add three new strings
translation
frontend
> [4.0] Global strings for readmore layout

- language/de-DE/mod_syndicate.ini
Pull Request für Issue #1173 .
translation
frontend
> [4.0] mod_syndicate a11y and more

- administrator/language/de-DE/com_cache.ini
> [4.0] will fix minor color contrast

- administrator/language/de-DE/de-DE.plg_fields_imagelist.ini
Pull Request für Issue #1380
Core language change
backend
> Remove reference to Media manager in Imagelist Custom Field 

- language/de-DE/mod_breadcrumbs.ini
Pull Request für Issue #1397
fehlende Zeile ergänzt
mit Core synchronisiert
> [4.0] missing string in mod_breadcrumps.ini

- administrator/language/de-DE/mod_user.ini
Pull Request für Issue #1406 .
fix wording
backend
> [4.0] fix wording accessibility settings

- .github/CONTRIBUTING.md
Der Link funktionierte mit : nicht daher durch / ersetzt.
> : durch / ersetzt

- installation/language/de-DE/joomla.ini
Pull Request für Issue #1433 .
fix
installation
> [4.0] delete punctuation after Website

- administrator/language/de-DE/de-DE.com_installer.ini
Pull Request für Issue #1531 .
add new string
translation
backend
> [staging] Displaying error when updating an extension/package

- administrator/language/de-DE/de-DE.com_config.ini
unification database tooltip
backend
> unification database tooltip

- administrator/language/de-DE/de-DE.com_joomlaupdate.ini
Pull Request für Issue #1552 .
fix a string
backend
> [3.10] Show the target version to the pre upgrade checker

- administrator/language/de-DE/com_associations.ini
Pull Request für Issue #1553 .
fix a string
backend
> [4.0] associations message

- administrator/language/de-DE/mod_latestactions.ini
Pull Request für Issue #1568 .
fix
backend
> [4.0] fix mod_latestactions.ini

- administrator/language/de-DE/com_csp.ini
- administrator/language/de-DE/plg_system_httpheaders.ini
Pull Request für Issue #1588 .
new links
backend
> [4.0] Change CSP docs links to Mozilla MDN

- administrator/language/de-DE/mod_version.ini
- administrator/language/de-DE/mod_version.sys.ini
Pull Request für Issue #1601 .
fix two strings
backend
> [4.0] latest version

- administrator/language/de-DE/de-DE.plg_system_privacyconsent.ini
Pull Request für Issue #1614 .
fix typo
Mail
> typo in de-DE.plg_system_privacyconsent

- administrator/language/de-DE/plg_system_skipto.ini
Pull Request für Issue #1623 .
fix strings, alpha ordering
backend
> [4.0] Skip to update

- administrator/language/de-DE/plg_system_skipto.ini
Pull Request für Issue #1635 .
fix typo
backend
> [4.0] skipto plugin typo

- administrator/language/de-DE/plg_actionlog_joomla.ini
Pull Request für Issue #1652
Fix #1652
> [4] Change action log wording of a failed login to admin console

- administrator/language/de-DE/plg_fields_subfields.ini
- administrator/language/de-DE/plg_fields_subfields.sys.ini
Pull Request für Issue #1675
fix #1675
> [4.0] Subforms/subfields

- administrator/language/de-DE/com_installer.ini
> [4] com_installer warnings empty state

- administrator/language/de-DE/plg_behaviour_taggable.ini
- administrator/language/de-DE/plg_behaviour_taggable.sys.ini
- administrator/language/de-DE/plg_behaviour_versionable.ini
- administrator/language/de-DE/plg_behaviour_versionable.sys.ini
> [4.0] behaviour plugin

- administrator/language/de-DE/com_mails.ini
Pull Request für Issue #1800 .
translation
backend
> [4] help text change for COM_MAILS_CONFIG_FIELD_ATTACHMENT_FOLDER_DESC

- administrator/language/de-DE/com_joomlaupdate.ini
Pull Request für Issue #1784  .
add target and rel
backend
> [4.0] pre-update check link

- administrator/language/de-DE/mod_stats_admin.sys.ini
- administrator/language/de-DE/mod_toolbar.ini
- administrator/language/de-DE/mod_toolbar.sys.ini
Pull Request für Issue #1838 .
fix two html entitie bugs
add one html entitie for sys.ini
backend
> [4.0] Module: "Statistiken", "Werkzeugleiste" zeigen HTML-Code

- administrator/language/de-DE/com_joomlaupdate.ini
Pull Request für Issue #1717
String aktualisiert
Backend
> [4.0] database fix text

- administrator/language/de-DE/mod_post_installation_messages.ini
- administrator/language/de-DE/mod_post_installation_messages.sys.ini
Pull Request für Issue #1725
Übersetzung angepasst
backend
> [4.0] Post installation module description

- installation/language/de-DE/joomla.ini
Pull Request für Issue #1749
fix link
backend
> [4.0] External link in installation message (a11y)

- administrator/language/de-DE/plg_webservices_banners.ini
- administrator/language/de-DE/plg_webservices_banners.sys.ini
- administrator/language/de-DE/plg_webservices_config.ini
- administrator/language/de-DE/plg_webservices_config.sys.ini
- administrator/language/de-DE/plg_webservices_contact.ini
- administrator/language/de-DE/plg_webservices_contact.sys.ini
- administrator/language/de-DE/plg_webservices_content.ini
- administrator/language/de-DE/plg_webservices_content.sys.ini
- administrator/language/de-DE/plg_webservices_languages.ini
- administrator/language/de-DE/plg_webservices_languages.sys.ini
- administrator/language/de-DE/plg_webservices_menus.ini
- administrator/language/de-DE/plg_webservices_menus.sys.ini
- administrator/language/de-DE/plg_webservices_messages.ini
- administrator/language/de-DE/plg_webservices_messages.sys.ini
- administrator/language/de-DE/plg_webservices_modules.ini
- administrator/language/de-DE/plg_webservices_modules.sys.ini
- administrator/language/de-DE/plg_webservices_newsfeeds.ini
- administrator/language/de-DE/plg_webservices_newsfeeds.sys.ini
- administrator/language/de-DE/plg_webservices_plugins.ini
- administrator/language/de-DE/plg_webservices_plugins.sys.ini
- administrator/language/de-DE/plg_webservices_privacy.ini
- administrator/language/de-DE/plg_webservices_privacy.sys.ini
- administrator/language/de-DE/plg_webservices_redirect.ini
- administrator/language/de-DE/plg_webservices_redirect.sys.ini
- administrator/language/de-DE/plg_webservices_tags.ini
- administrator/language/de-DE/plg_webservices_tags.sys.ini
- administrator/language/de-DE/plg_webservices_templates.ini
- administrator/language/de-DE/plg_webservices_templates.sys.ini
- administrator/language/de-DE/plg_webservices_users.ini
- administrator/language/de-DE/plg_webservices_users.sys.ini
Pull Request für Issue #1741
Übersetzungen editiert
backend
> [4.0] plg_webservices descriptions

- administrator/language/de-DE/plg_installer_folderinstaller.ini
- administrator/language/de-DE/plg_installer_folderinstaller.sys.ini
Pull Request für Issue #1739
Übersetzungen aktualisiert
Backend
> [4.0] Install from folder

- administrator/language/de-DE/com_messages.ini
Pull Request für Issue #1867 .
add new string
translation
backend
> [4.0] Messaging : options missing string

- administrator/language/de-DE/mod_messages.ini
- administrator/language/de-DE/mod_messages.sys.ini
- administrator/language/de-DE/mod_post_installation_messages.ini
- administrator/language/de-DE/mod_post_installation_messages.sys.ini
- administrator/language/de-DE/mod_version.ini
- administrator/language/de-DE/mod_version.sys.ini
Pull Request für Issue #1893 .
fix some strings
backend
> [4.0] admin module descriptions

- installation/language/de-DE/joomla.ini
Pull Request für Issue #1894 .
fix strings
installation
> [4.0] add rel attribute in joomla.ini

- administrator/language/de-DE/mod_login.sys.ini
Pull Request für Issue #1926
Fehler im Language-String behoben.
Vorhandenen Text gekürzt
Backend
> [4.0] Dialogue Add module

- administrator/language/de-DE/com_installer.ini
Pull Request für Issue #1937
Link aktualisiert
Backend
> [4.0] Translation links
